name: Sync Repository

on:
  push:
    branches:
      - main # Adjust branch name as needed
#no
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: Hussain-L/repo-2
          token: ${{ secrets.SECOND_REPO_TOKEN }}

      - name: Pull changes from source repository
        run: |
          echo "First line"
          git remote add source https://github.com/Hussain-L/repo-1
          git fetch source
          git checkout branch-1
          git pull --rebase source branch-1

      - name: Push changes to target repository
        run: |
          git push origin branch-1


