name: Sync Repository

on:
  push:
    branches:
      - main # Adjust branch name as needed
#no
jobs:  
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: Hussain-L/repo-2
          token: ${{ secrets.SECOND_REPO_TOKEN }}

      - name: Pull changes from source repository
        run: |
          echo "First line"
          cat README.md
          git remote add source https://github.com/Hussain-L/repo-1
          git fetch source
          git pull source main
          cat README.md
          pwd
          ls -la

      - name: Push changes to target repository
        run: |
          pwd
          ls -la
          git push origin main


